import type { ModuleContent } from './types';

export const hmmContent: ModuleContent = {
  id: 'hmm',
  title: 'Hidden Markov Models',
  subtitle: 'Temporal Reasoning · Chapter 15',

  overview: {
    paragraphs: [
      'Hidden Markov Models (HMMs) are probabilistic models for temporal sequences where the true state of the world is hidden and we only observe noisy evidence. At each timestep, the state evolves according to a transition model P(X_t | X_{t-1}), and we receive an observation from the emission model P(E_t | X_t). The core inference task is filtering: computing the belief state P(X_t | e_{1:t}) — the posterior distribution over the current hidden state given all past observations.',
      'The Forward algorithm performs exact filtering by recursively updating the belief: predict the next state by marginalizing over the transition model, then update by multiplying with the observation likelihood. The normalization constant at each step is the probability of the new evidence given past observations, and multiplying these gives the total likelihood P(e_{1:T}) — a key quantity for model comparison and learning.',
      'The Viterbi algorithm answers a different question: instead of computing the posterior distribution (summing over all possible paths), it finds the single most likely state sequence that explains the observations (maximizing over paths). This is the MAP estimate x_{1:T}^* = argmax P(x_{1:T} | e_{1:T}), and is solved via dynamic programming with backtracking.',
      'HMMs are foundational for speech recognition, natural language processing, bioinformatics, and robotics. The robot localization example demonstrates how filtering enables spatial reasoning under uncertainty: movement increases entropy (diffuses the belief), and sensing decreases entropy (sharpens the belief toward the true location).',
    ],
    equations: [
      {
        label: 'Transition model',
        latex: 'P(X_t | X_{t-1})',
        explanation: 'First-order Markov assumption: the next state depends only on the current state, not the full history.',
      },
      {
        label: 'Emission model',
        latex: 'P(E_t | X_t)',
        explanation: 'Observation depends only on the current hidden state — conditionally independent of past states given X_t.',
      },
      {
        label: 'Forward algorithm (filtering)',
        latex: 'B(X_t) = \\alpha\\, P(e_t | X_t) \\sum_{x_{t-1}} P(X_t | x_{t-1})\\, B(x_{t-1})',
        explanation: 'Recursive Bayesian update: predict by marginalizing over transitions, update by multiplying with observation likelihood, normalize with α.',
      },
      {
        label: 'Viterbi algorithm (most likely path)',
        latex: 'V_t(x_t) = P(e_t | x_t) \\max_{x_{t-1}} P(x_t | x_{t-1})\\, V_{t-1}(x_{t-1})',
        explanation: 'Replace sum with max to find the single best path. Store backpointers for traceback after the forward pass.',
      },
    ],
    keyInsights: [
      'Forward sums over paths; Viterbi maximizes. The Viterbi path probability is always ≤ the total likelihood.',
      'Filtering smooths out noisy observations by propagating belief through the transition model — watching the trellis diagram makes this vivid.',
      'In robot localization, movement without sensing causes the belief to diffuse (entropy increases). Sensing a distinctive feature (e.g., a corner) causes the belief to collapse to a sharp peak (entropy decreases). This is the "kidnapped robot" problem.',
      'The likelihood P(e_{1:T}) is the product of normalization constants from each step. Low likelihood → the model does not fit the data well.',
      'Adjust the transition/emission matrices and observe how the trellis structure changes. If a transition probability goes to zero, the corresponding edge disappears — this is the conditional independence structure at work.',
    ],
  },

  algorithm: {
    name: 'HMM Algorithms: Forward, Viterbi & Localization',
    complexity: 'O(T · |X|²) time for Forward & Viterbi',
    steps: [
      { kind: 'header', indent: 0, text: '1. Forward Algorithm (Filtering)' },
      { kind: 'io', indent: 0, text: 'Input: observations e_{1:T}, transition P(X_t|X_{t-1}), emission P(E_t|X_t), prior P(X_0)' },
      { kind: 'io', indent: 0, text: 'Output: filtered beliefs B(X_t) = P(X_t | e_{1:t}) for t = 1…T' },
      { kind: 'divider', indent: 0, text: '' },
      { kind: 'step', indent: 0, text: 'Initialise: B(X_0) ← P(X_0)' },
      { kind: 'step', indent: 0, text: 'For t = 1 to T:' },
      { kind: 'comment', indent: 1, text: '── Predict ──' },
      { kind: 'step', indent: 1, text: 'B\'(X_t) ← Σ_{x_{t-1}} P(X_t | x_{t-1}) B(x_{t-1})' },
      { kind: 'comment', indent: 1, text: '── Update ──' },
      { kind: 'step', indent: 1, text: 'B(X_t) ← P(e_t | X_t) · B\'(X_t)' },
      { kind: 'comment', indent: 1, text: '── Normalize ──' },
      { kind: 'step', indent: 1, text: 'α ← 1 / Σ_x B(x)' },
      { kind: 'step', indent: 1, text: 'B(X_t) ← α · B(X_t)' },
      { kind: 'step', indent: 0, text: 'Return B(X_1), …, B(X_T)' },
      { kind: 'divider', indent: 0, text: '' },
      { kind: 'header', indent: 0, text: '2. Viterbi Algorithm (Most Likely Path)' },
      { kind: 'io', indent: 0, text: 'Input: same as Forward' },
      { kind: 'io', indent: 0, text: 'Output: most likely state sequence x_{1:T}^*' },
      { kind: 'divider', indent: 0, text: '' },
      { kind: 'step', indent: 0, text: 'Initialise: V_0(x) ← P(x) for all x' },
      { kind: 'step', indent: 0, text: 'For t = 1 to T:' },
      { kind: 'step', indent: 1, text: 'For each state x_t:' },
      { kind: 'comment', indent: 2, text: '── Max instead of Sum ──' },
      { kind: 'step', indent: 2, text: 'V_t(x_t) ← P(e_t | x_t) max_{x_{t-1}} [P(x_t | x_{t-1}) V_{t-1}(x_{t-1})]' },
      { kind: 'step', indent: 2, text: 'backpointer[t, x_t] ← argmax_{x_{t-1}} [P(x_t | x_{t-1}) V_{t-1}(x_{t-1})]' },
      { kind: 'comment', indent: 1, text: '── Traceback ──' },
      { kind: 'step', indent: 0, text: 'x_T^* ← argmax_{x_T} V_T(x_T)' },
      { kind: 'step', indent: 0, text: 'For t = T-1 down to 0:' },
      { kind: 'step', indent: 1, text: 'x_t^* ← backpointer[t+1, x_{t+1}^*]' },
      { kind: 'step', indent: 0, text: 'Return x_{0:T}^*' },
      { kind: 'divider', indent: 0, text: '' },
      { kind: 'header', indent: 0, text: '3. Robot Localization (2D HMM)' },
      { kind: 'io', indent: 0, text: 'Input: grid world, action, sensor reading' },
      { kind: 'io', indent: 0, text: 'Output: updated belief over robot position' },
      { kind: 'divider', indent: 0, text: '' },
      { kind: 'step', indent: 0, text: 'Initialise: B(cell) ← uniform over free cells' },
      { kind: 'step', indent: 0, text: 'On action (move):' },
      { kind: 'comment', indent: 1, text: '── Prediction with noise ──' },
      { kind: 'step', indent: 1, text: 'For each cell c:' },
      { kind: 'step', indent: 2, text: 'B\'(c) ← Σ_{c\' adjacent} P(c | c\', action) B(c\')' },
      { kind: 'step', indent: 2, text: 'where P includes action noise' },
      { kind: 'step', indent: 0, text: 'On sensor reading (walls detected):' },
      { kind: 'comment', indent: 1, text: '── Update with sensor model ──' },
      { kind: 'step', indent: 1, text: 'For each cell c:' },
      { kind: 'step', indent: 2, text: 'B(c) ← P(sensor | c) · B(c)' },
      { kind: 'step', indent: 1, text: 'Normalize B(c)' },
      { kind: 'comment', indent: 0, text: 'Entropy H = -Σ B(c) log B(c) tracks uncertainty' },
    ],
    note: 'Forward computes full posterior (sum over paths); Viterbi finds single best path (max over paths). Robot localization demonstrates entropy: movement increases it, sensing decreases it.',
  },



  references: [
    {
      label: 'Artificial Intelligence: A Modern Approach',
      authors: 'S. Russell, P. Norvig (Pearson, 2020)',
      url: 'https://aima.cs.berkeley.edu/',
      description: 'Chapter 14: Probabilistic Reasoning over Time. The definitive introduction to HMMs, filtering, and the Forward-Backward algorithm.',
      type: 'book',
    },
    {
      label: 'Probabilistic Artificial Intelligence — Krause & Hübotter',
      authors: 'A. Krause, J. Hübotter (ETH Zürich, 2025)',
      url: 'https://arxiv.org/abs/2502.05244',
      description: 'Lecture 15: Temporal Models. HMMs, filtering, and the relationship to Kalman filters and particle filters.',
      type: 'book',
    },
    {
      label: 'Machine Learning: A Probabilistic Perspective',
      authors: 'K. Murphy (MIT Press, 2012)',
      url: 'https://probml.github.io/pml-book/',
      description: 'Chapter 17: Markov and Hidden Markov Models. Comprehensive treatment of HMMs with applications to speech and NLP.',
      type: 'book',
    },
  ],
};
